### ISSUE TITLE
Downloading Spectral for Linux fails in versions 6.7+

### ISSUE THREAD

**Issue by icod** [michael-nestler/gradle-spectral#1]
Downloading Spectral from the task `spectralDownload` fails from Spectral version [6.7.0](https://github.com/stoplightio/spectral/releases/tag/v6.7.0) onwards, since the asset names are now suffixed with the system architecture, e.g. 'spectral-linux-x64', 'macos-linux-x64'.

**Comment by michael-nestler** [comment]
Thanks for the detailed report, can you try with `0.0.0-8`? I'll bump the version to `0.1.0` once you can confirm this works for you

**Comment by icod** [comment]
Hi Michael, thanks for your swift reaction (and the plugin as a whole!)

I have tried `0.0.0-8` and can confirm that it now works with Spectral versions `6.7.0` through `6.11.0` on Windows, and with version `6.11.0` on Linux (amd64). 👍 

Looking forward to the `0.1.0` release!

**Comment by michael-nestler** [comment]
Released https://plugins.gradle.org/plugin/io.github.michael-nestler.spectral/0.1.0
